# Generated by Django 5.0.7 on 2024-08-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, related_name='parents', through='Card.Relation',
                                         to='Card.card'),
        ),
    ]
