# Generated by Django 5.0.7 on 2024-08-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Card', '0002_alter_card_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='parents', through='Card.Relation', to='Card.card'),
        ),
    ]
