# Generated by Django 5.0.7 on 2024-09-12 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0005_card_priority_remember_tag_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('tag', 'card')},
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('full_time', models.BooleanField(default=False)),
                ('start', models.DateTimeField(blank=True)),
                ('end', models.DateTimeField(blank=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Card.card')),
            ],
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
