# Generated by Django 5.0.7 on 2024-09-13 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0006_alter_tag_unique_together_todo_delete_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('time', models.DateTimeField(null=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Card.card')),
            ],
            options={
                'unique_together': {('card', 'time', 'state')},
            },
        ),
        migrations.DeleteModel(
            name='Remember',
        ),
    ]
