# Generated by Django 5.0.7 on 2024-09-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0008_relation_priority_tag_priority_todo_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
