# Generated by Django 5.0.7 on 2024-09-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0009_relation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
